### ISSUE TITLE
Invalid search field used for request with hidden fields

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1025]
Context :
* a table with 3 searchable columns : id, name, author
* column id is hidden

When doing a search on name column, the list sends a search request for the id column.
When doing a search on author column, the list sends a search request for the name column.

It seems that, when having an hidden column on the left side of the column, the request sent doesn't take the expected field but takes the field at index - N hidden fields on the left side.

**Comment by itkg-alavieille** [comment]
it's fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1036
