### ISSUE TITLE
As a frontend integrator, I want to add additional loadExtendView in activateForm method

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1028]
In the goal of adding additionnal events for specific forms without having to change / duplicate the function.

See: orchestraLib.coffee

**Comment by nicolasThal** [comment]
A solution would be to add a configuration for all the event to launch when we activate a form (ie: select2, tinymce, colorpicker, ...)

That would allow the developer to modify or add new events on the form

**Comment by itkg-nanne** [comment]
In orchestraView.coffe, OnOrchestraViewReady load different components to activate the form. After it a onViewReady is called. This workflow could be seen in widgetChannle.coffee. Initially, onViewReady is empty and this function must be overridden to add your custom components. @nicolasThal , @clement-michelet
