### ISSUE TITLE
Infinite loop on action urls

### ISSUE THREAD

**Issue by bdremynoel** [open-orchestra/open-orchestra-cms-bundle#1032]
Hello,

If we call directly an url action for example with no context, this generates infinite loops when rendering the page.

Here's samples of fake direct calls to reproduce the case:
http://xyz.com/admin/#slide_deck/add
http://xyz.com/presentations/#slide_deck/edit/55e022981d9e9a70778b4567/version_1

Steps to reproduce:
1- get this kind of url
2- logout the current user
3- login again
4- paste the url copied in step 1
5- voilà !

**Comment by juchi** [comment]
seems to be an issue on MH side, I will investigate

**Comment by juchi** [comment]
Bug spotted, the "data-add" url was missing on our custom menu entries.
@nicolasThal I guess this is problematic that we get a JS loop in this case though...

**Comment by nicolasThal** [comment]
This has been put in the roadmap, we will keep you posted

**Comment by itkg-nanne** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1068
