### ISSUE TITLE
Remove widgetStatus id in widgetStatus view

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1065]
In: https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/BackofficeBundle/Resources/views/BackOffice/Underscore/widgetStatus._tpl.twig

I don't have found yet an use of the id `widgetStatus`. If I want to use the StatusView multiple times in the same page/view, the id must be removed.

**Comment by itkg-alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1066
