### ISSUE TITLE
The ValueTransformerManager does not always return a string

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1087]
When creating a custom form type for a field in a content type, if the value cannot be casted to a string (an array in my case), then the transform() method will return this value, which will result in an error when saving the stringValue attribute in the DB. (Unless of course a strategy has been added for this custom field).
The ValueTransformerManager should always return a string, even empty, according to its api.

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/Backoffice/ValueTransformer/ValueTransformerManager.php#L34 send an exception  or an empty string if the `$value` is not a string.

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1119
