### ISSUE TITLE
Afficher / masquer le champs de recherche globale

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1091]
Il faudrait pouvoir masquer le champs de recherche globale via l'entrée du menu (par défaut: afficher).

**Comment by itkg-alavieille** [comment]
it's fixed in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1164

By default the global search field is hidden, you can use the data attribute ``display-global-search`` in the link of navigation panel to show it in the table view
