### ISSUE TITLE
Afficher / masquer un champs de recherche pour une colonne

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1092]
Il faudrait pouvoir masquer un champs de recherche si la recherche n'est pas activée sur la colonne (annotation, autre, etc.).

Par défaut, la recherche ne devrait pas être active sur une colonne affichée.

**Comment by nicolasThal** [comment]
This might be done in 1.1

**Comment by itkg-alavieille** [comment]
added in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1205
and for the documentation : https://github.com/open-orchestra/open-orchestra-docs/pull/132
