### ISSUE TITLE
Recherche par date sur une colonne

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1093]
Il serait bien de pouvoir rechercher par date sur des colonnes de types dates (à partir de, jusqu'à, entre).

**Comment by nicolasThal** [comment]
This might be done in the 1.1 version

**Comment by itkg-alavieille** [comment]
added in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1205
and for the documentation : https://github.com/open-orchestra/open-orchestra-docs/pull/132
