### ISSUE TITLE
Impossible de désélectionner une page source (en cas de copie)

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1106]
Lors de la création d'une nouvelle page, on peut partir d'un gabarit ou d'une page existante. Si l'on sélectionne une page source, on ne peut pas la désélectionner une fois celle-ci choisie.

**Comment by itkg-alavieille** [comment]
fix in this PR : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1109

**Comment by itkg-mraiffe** [comment]
:+1:
