### ISSUE TITLE
User Group does not required site field 

### ISSUE THREAD

**Issue by pdenis** [open-orchestra/open-orchestra-cms-bundle#1120]
Hi,
When no site is selected for a User group. I Have this error : 

01.5:42401] PHP Fatal error:  Call to a member function getSiteId() on a non-object in /var/www/mhis-mhps/shared/vendor/open-orchestra/open-orchestra-cms-bundle/OpenOrchestra/BackofficeBundle/Security/Authorization/Voter/GroupSiteVoter.php on line 93, referer: http://admin.mhps.interakting.org/login

May the site field be required in the group form ?

**Comment by itkg-ngilain** [comment]
Hi, the problem was spotted in a previous version. We applied a patch to let the site optionnal, but for some reason it seems there is still a bug with the login. We're looking at it and will produce a fix asap.

Thank you for your report.

**Comment by itkg-alavieille** [comment]
fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1135 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1134
