### ISSUE TITLE
A group can be removed but the users are not detached from it

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1156]
I am able to remove any user group in the Groups menu.
However, doing so on a group that it linked to some users will result in the Users menu being broken (and probably other features too) because the users have DBRef to an unexisting document.

**Comment by itkg-nanne** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1199
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/79
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1198
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/78
