### ISSUE TITLE
Allow to select date using a datepicker

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1162]
The date field is currently composed of 3 fields : day, month, year. It take many unnecessary spaces and is not pretty looking.

![capture du 2015-10-29 10 46 14](https://cloud.githubusercontent.com/assets/4611569/10815125/4bd8b8d4-7e2a-11e5-8a84-e89736356a3c.png)

It could be great to :
* Display the 3 select fields in one line
* Add a datepicker button to use a datepicker to select date

**Comment by itkg-nanne** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1303
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1302
