### ISSUE TITLE
Grid filters generate too many requests

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1171]
When using a filter on a grid, a request is sent for each character typed in the search area. It would save LOTS of query to wait for a little delay (like 300ms maybe) after the latest keyboard entry.

**Comment by juchi** [comment]
It should also be noted that the results are displayed according to the latest _received_ ajax response, not the latest request sent (i.e. I send search requests A, B, C, and receive A then C then B, B's results will remain displayed, which is incorrect).

**Comment by itkg-alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1194

**Comment by itkg-alavieille** [comment]
This changes are revert https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1196

**Comment by itkg-alavieille** [comment]
It's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1295/files
if there are already a request sent, she is aborted before send a new request
