### ISSUE TITLE
Spacing in grids header

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1188]
Can we cherry pick this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1154/ into the 1.0 branch please ?

**Comment by itkg-alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1206

**Comment by juchi** [comment]
thank you
