### ISSUE TITLE
JS error in Node form

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1192]
When you focus on the Page field in Node form and leave the field without setting any value, a JS error occurred:
`Cannot read property 'latinise' of undefined`.

![capture du 2015-11-09 10 01 59](https://cloud.githubusercontent.com/assets/4611569/11029713/17788892-86c9-11e5-89c8-c42b5bd15211.png)

**Comment by itkg-alavieille** [comment]
it's fix in this PR : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1207
