### ISSUE TITLE
Keep column status on client side

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1217]
When an user enable a column in an entity list and leave the page, the status of the column is reset to it's original state (disabled).

When you re-open the list, it's annoying to have to enable the column again.
It could be great to keep this status during a set of time using cookie, local storage or any other storage on client side.

**Comment by itkg-alavieille** [comment]
added in this PR :https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1260
