### ISSUE TITLE
Issue with the contentType edition

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1233]
In my case : 

 - my backOffice in French only
 - When I create a contentType, everything works fine
 - When I want to edit it, I have an issue with the getName method (the base language is 'en' and it does not exits)

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/473

I have provided a fix, it will be available in the 1.1.0-alpha-2 tag.

The issue occured when the display event was catched by the logging bundle

**Comment by nicolasThal** [comment]
My bad, the fix will be in this pr : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1234
