### ISSUE TITLE
Move node after it creation won't work

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1257]
I can't move nodes after creating them.
1. create 2 nodes (select a page source)
2. move them in the navigation three => the node can't be move
This bug is visible on Firefox and Chrome

**Comment by itkg-alavieille** [comment]
it's fix in this pr https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1283/files
