### ISSUE TITLE
Support: Refresh a tab in form

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1313]
With the current implementation of tabbed form in the CMS, is it possible to pragmatically ask to refresh a tabs ?

We have a case where we want to refresh a tab when an action is triggered on an another page.

**Comment by itkg-alavieille** [comment]
The various implementations of tab forms (users,media ) use a generic mechanism that allows have a Backbone view for each tab.

There is a view `TabView` that represent a view with multiple tabs, this view has a method `addPanel(title, id, view, active, position)`  to add a tab.

 * title (string) : tab's title
 * id (string) : tab's id
 * view (BackboneView): view of tab's content
 * active (boolean): indicate if the tab is active or not
 * position: position of tabs relative to the others tabs

So, you can create a specific backbone view for your tab with your you case.

**Comment by clement-michelet** [comment]
Thanks, I will check this solution.
