### ISSUE TITLE
Save a tab in tabbed form add a new tab

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1314]
Tested on: http://demo.open-orchestra.com/admin/#user/edit/5667f9a4bfdb0312518b4c8d

If you save the form, instead of replacing the current tab, it will add a tab next to the current tab. See attachment.

![capture d ecran de 2015-12-18 11 32 32](https://cloud.githubusercontent.com/assets/4611569/11894965/0a4ebe90-a57b-11e5-83dc-9f0084bf8541.png)

**Comment by itkg-alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1321 and 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1299
