### ISSUE TITLE
Tabbed forms generate two request for _self_form link

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1394]
Version: 1.0.3, 1.1.0-DEV
When I open any tabbed form (tested in custom and OO user), I see in XHR logs that the `_self_form` form is loaded twice.

It should not be the case.

**Comment by itkg-nanne** [comment]
fix by https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1404
