### ISSUE TITLE
Node delete, cannot recreate a node with the same route

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1415]
I have deleted a node, then when I recreate a node, I cannot specify the same routePattern

**Comment by alavieille** [comment]
nodes are softdeletable, so they are never deleted they are added to the trashcan, in this PR i have updated the message to indicate if the node is in the trashcan. 

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/533

we will also make possible the removal a trash node
