### ISSUE TITLE
Delete action on table view redirect to first page

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1437]
Version: 1.1.0-alpha4
Tested on http://demo.open-orchestra.com/admin/#keywords/list/2

When I delete an element in a table view which is at a page with an index greather than 1, I'm automatically redirected to the first page of the table view. This is not user friendly to force the user to go back to the previous page when you want to delete multiple items.

Could you keep the current page displayed after deletion ?

**Comment by alavieille** [comment]
There is fixed in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1821. thanks
