### ISSUE TITLE
FormType Collection - bug when removing and adding an element

### ISSUE THREAD

**Issue by itk-hlechevallier** [open-orchestra/open-orchestra-cms-bundle#1469]
Here is how to reproduce this bug:
In a form type collection I add three elements (elem0, elem1, elem2).
I remove the second one (elem1).
Then I add a new one (elem3).
After saving the form, we only have two elements in the collection: elem0, elem3.
We were expecting three elements: elem0, elem2, elem3.

Notes: 
- The collection is a collection of text elements.
- Open orchestra version: v1.0.2.

**Comment by itkg-ngilain** [comment]
We are fixing this.

**Comment by itkg-nanne** [comment]
fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1483
