### ISSUE TITLE
Group administration : display Front roles in a new tab

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1478]
In alpha-4 the front roles are not visible in the group administration feature. Maybe it should be user-friendly to dissociate de back and front roles in different tabs?

**Comment by alavieille** [comment]
We might do this in OO 1.2

**Comment by betd-rcarles** [comment]
The front roles are displayed in 1.1 in a sub-category, the tab will be implemented int 1.2
