### ISSUE TITLE
Twig variable visible in a form twig but not in the file that contains block templates

### ISSUE THREAD

**Issue by itk-hlechevallier** [open-orchestra/open-orchestra-cms-bundle#1492]
In the main twig file we can display this variable we can from the controller:
`{{ cheapestVersionId }}`

But in the twig template file we define a block like this:
`{% block dsin_equipments_category_formtype_widget %}
    {% spaceless %}
        {% for key, field in form %}
            {{ form_row(field) }}
        {% endfor %}
    {% endspaceless %}
    <tr><td><img src="http://www.test.fr/img?version={{ cheapestVersionId }}" class="img_preview_model" /></td><td></td><td></td></tr>
{% endblock %}`

and got an error:
 Variable "cheapestVersionId" does not exist in DsinRangeManagerBundle:BackOffice/Underscore:rangeManagerFormView._tpl.twig at line 545
500 Internal Server Error - Twig_Error_Runtime 

I found a way to update the image src attribute using jquery but this code is not clean.
Is there a better way to pass this variable using coffee?

**Comment by itkg-nanne** [comment]
Not sure that this question is in relation with Open Orchestra Kernel. Any Way, in the php Form Type corresponding to dsin_equipments_category_formtype_widget, you can use buildView to add parameters to your twig. You can find an example here :
Definition : https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/Backoffice/Form/Type/Component/ContentSearchType.php (line 85)
Used : https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/BackofficeBundle/Resources/views/Form/form_div_layout.html.twig (line 118)
