### ISSUE TITLE
`ContentTypeEvents::CONTENT_TYPE_UPDATE` event dispatched in a wrong context

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1511]
The `ContentTypeEvents::CONTENT_TYPE_UPDATE` event is dispatched when opening content type form in backoffice interface. It should only be dispatched when this form is submitted.

**Comment by alavieille** [comment]
It's fixed in PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1505
