### ISSUE TITLE
Block max age default value

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1524]
Default max age value for a block is ambiguous.
When editing a block parameters for the first time, field "maxAge" is empty, If no value is set into the form, then a "0" value is store in DB. Is this "0" value a "special" value or is it just the value that is sent in HTTP headers ?
If it is the value sent in HTTP headers, it means that if user does not define a max age, then there is no cache on this block. As BO users usually not aware of what a "cache" is, I think they will let this field empty in most of cases.

**Comment by itkg-ngilain** [comment]
0 is not a special value, it's a 0 second cache value.

We will think about a more accurate settings of this in the branch 1.2

**Comment by alavieille** [comment]
There is fixed in 2.0
