### ISSUE TITLE
It is impossible to override default block form fields

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1525]
The mechanism used to build block forms give no possibility to the developer to override anything that came from the "oo_block" form type.
I could be useful to be able to access to base fields inside the `GenerateFormInterface::buildForm()` method.
For example :
```
if ($builder->has('maxAge')) {
    $builder->get('maxAge')->setAttribute('readonly', 'readonly');
    $builder->get('maxAge')->setData(60);
}
```

I wanted to define "maxAge" field as readonly with a forced value, but it is not possible.

**Comment by itkg-ngilain** [comment]
For the moment, you can do what you want by redefining the max-age component in your strategy. That way, it will replace the native max-age component
