### ISSUE TITLE
Cache tags/invalidation documentation missing

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1527]
I have to define all cache tags of my blocks and I do not found any documentation that lists cache tags nomenclature and operations that leads to an invalidation of cache.

It can be useful for a developer to know how to build its cache tags.

By the way, I search in the code and I did not found any invalidation based on tags that can be build using following methods of `OpenOrchestra\BaseBundle\Manager\TagManager` :

- formatLanguageTag
- formatSiteIdTag
- formatBlockTypeTag
- formatContentTypeTag

Is it a missing feature ?

**Comment by alavieille** [comment]
A first part of this issue is fixed in this PR https://github.com/open-orchestra/open-orchestra-docs/pull/200

I have added documentation for describe the tags provides by the TagManager

**Comment by alavieille** [comment]
This is fixed in this PR 
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/109
