### ISSUE TITLE
Content list not filtered in configurable content

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1529]
In configurable content block.
On demo site
 - When i choose a content type, xmlHttp request has been send and then return content list filtered by contentType but html select element is not refresh
 - When i choose a content type, for Exemple Car and I choose a car content. I submit the block.
When I re open the same block, content Type Car is selected but content list is not filtered

**Comment by alavieille** [comment]
This is fixed, configurable content use now content search 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1693
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/220
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1683
