### ISSUE TITLE
Add wide range cache tags

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1532]
On our project, we have a lot of cases where cache invalidation has to be made using "wide range" tags. I think it is a common usage, and maybe having it inside open orchestra core could be valuable.

Here is a lot of example :
 - website map block cache as to be invalidated every time a node is created/updated/deleted (*),
 - content search result block cache has to be invalidated every time a content is created/updated/deleted (*),
 - document library block cache has to be invalidated every time a content of type "Document" is created/updated/deleted (*),
 - event timeline block (a block that displays a timeline of events) cache has to be invalidated every time a content of type "Event" is created/updated/deleted (*),
 - ...

(*) "updated" refers to an update that changes published elements.

**Comment by alavieille** [comment]
This is fixed in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1568. thanks
