### ISSUE TITLE
Try to access getAccessType on nodeGroupRole when is null

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1533]
In oo - 1.1.0-alpha4
In updateNodeGroupRoleTree method which is in UpdateNodeGroupRoleMoveNodeSubscriber

$nodeGroupRole = $group->getNodeRoleByNodeAndRole($node->getNodeId(), $role); could be null
If we try to access getAccessType() on null, error 500 display.

It would be preferable to throw an Exception when $nodeGroupNode is null as nodeGroupNodeParent three lines below

**Comment by alavieille** [comment]
normally it was fixed in beta version, an exception ``NodeGroupRoleNotFoundException`` is throw.
