### ISSUE TITLE
check node order only on nodetype "page"

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1536]
When I want to save my root node I have an error because my 404 error node have the same order than my root node. 
But error404 node is of type "error" not "page" like my root node.

Maybe you should check the nodeType + order + parentId when saving node.

**Comment by alavieille** [comment]
it's fixed in this PR https://github.com/open-orchestra/open-orchestra-model-bundle/pull/545. thanks
