### ISSUE TITLE
Deleted transverse blocks do not disappear after their remove from transverse page

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1538]
1. I add a new block in the transverse page
2. I see the blue block in the list of available blocks in node pages
3. I remove the block from the transverse page
4. I always see the blue block in the list of available blocks in node pages

**Comment by alavieille** [comment]
There is fixed in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1599

**Comment by itkg-mraiffe** [comment]
:+1:
