### ISSUE TITLE
Internet Explorer 11 : Node admnistration : the blocks are superimposed

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1541]
When I open Open-Orchestra nodes, in IE 11 the blocks are superimposed.
![capture du 2016-04-04 11 09 25](https://cloud.githubusercontent.com/assets/5470027/14243472/0a98d2ac-fa56-11e5-9f86-2b8b4f366c77.png)

**Comment by alavieille** [comment]
can you test in beta version ?  this bug is normally fixed.

**Comment by itkg-mraiffe** [comment]
No bug in beta version. Thanks
