### ISSUE TITLE
Not possible to overload BlockToArrayTransformer

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1579]
In BlockType class and in method buildForm, an addViewerTransformer is calling with new BlockToArrayTransformer() in parameter.

I think BlockToArrayTransformer must be injected by a service.

**Comment by itkg-nanne** [comment]
solve by https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1608
