### ISSUE TITLE
TransformerParameterTypeException namespace

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1598]
I think the `OpenOrchestra\ApiBundle\Exceptions\TransformerParameterTypeException`  should be declared in the `BaseApi` bundle `OpenOrchestra\BaseApi\Exceptions`. The app can't currently throws the exception in `OpenOrchestra\BaseApi\Transformer\AbstractTransformer::newFacade()` if it don't includes the `ApiBundle`.

**Comment by alavieille** [comment]
This is fixed in this PR :https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/80
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/214
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1623

thanks.
