### ISSUE TITLE
Saving problems on 'collection' type field that contains a 'oo_tinymce'

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1603]
When I create multiples elements inside a collection of items that contains a 'oo_tinymce' field type, all of them are not saved completely.

To reproduce this :
 - create a type 'SomeType' that contains a field of type 'oo_tinymce',
 - create a field type 'SomeCollectionType' that is a collection of 'SomeType',
 - create a content type that has an attribute of type 'SomeCollectionType',
 - create an instance of this content type and create 3 items of type 'SomeType'
 - fill the first one,
 - fill the third one,
 - fill the second one and click "save" directly
-> the second one is not saved.

I used Ubuntu 14.04 / Firefox 45 / OO dev-master (cms-bundle having rev. 4b37a6283bd96885964c4f71a5dd298aee28a37f).

It looks like the order has an importance, but I really do not understand why.

**Comment by itkg-nanne** [comment]
fixed by :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1629
