### ISSUE TITLE
Error when deleting a collection item having a 'oo_tinymce' field.

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1604]
When I create multiples elements inside a collection of items that contains a 'oo_tinymce' field type and try to remove one, form submission fails.

To reproduce this :
 - create a type 'SomeType' that contains a field of type 'oo_tinymce',
 - create a field type 'SomeCollectionType' that is a collection of 'SomeType',
 - create a content type that has an attribute of type 'SomeCollectionType',
 - create an instance of this content type and create 2 items of type 'SomeType'
 - save content,
 - open update form of this content,
 - delete one of the items,
 - submit the form.
-> A javascript error is triggered.

I used Ubuntu 14.04 / Firefox 45 / OO dev-master (cms-bundle having rev. 4b37a6283bd96885964c4f71a5dd298aee28a37f).

**Comment by itkg-nanne** [comment]
fixed by :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1629
