### ISSUE TITLE
Block reference error on create new node version

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1636]
Error 500 when we create a new version of a node.

You can reproduce the case following those steps:
- Create a node 
- Add 3 blocks to it
- Remove the second block
- Create a new version of the node

Error: Call to a member function getAreas() on null
vendor/open-orchestra/open-orchestra-cms-bundle/Backoffice/Manager/NodeManager.php at line 416

**Comment by alavieille** [comment]
This is fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1648 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1647
