### ISSUE TITLE
Cannot use ConfigurableContentStrategy data from 1.1.0-alpha4 in 1.1.0

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1642]
We found structure changes in ConfigurableContentStrategy betweend 1.1.0-alpha4 and 1.1.0. It seems like all fields are moved in a  oo_content_search form. contentId is not registered in the same way in database
"contentSearch" : {
                    "contentType" : "RichText",
                    "choiceType" : "",
                    "keywords" : "",
                    "contentId" : "5729ffb0749a1b14008b4568"
                },
There is not an migration script to update Configurable contents in 1.1.0 and all data would be lost. It's possible to make a migration script?

**Comment by alavieille** [comment]
This is fixed in this PR https://github.com/open-orchestra/open-orchestra-model-bundle/pull/577
