### ISSUE TITLE
Node root not visible when creating a new Website

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1651]
When I create a new WebSite, the node root page and the "create new page" button are not visible. We cannot create the site tree.

**Comment by alavieille** [comment]
This is fixed in this PR 
https://github.com/open-orchestra/open-orchestra-model-interface/pull/183
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1654
