### ISSUE TITLE
Choice type multiple expand problem

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1663]
Since the 1.1.0 RC, all choice types with options `multiple=true` and `expanded=true` doesn't works correctly. It works with options `multiple=true` and `expanded=false`.

When we save the block containing the type, checkboxes with value `off` disappear.
If the first checkbox isn't selected and others selected an invalid form error is throw.
I think there's a transform problem.

**Comment by itkg-canne** [comment]
I reproduced it on http://admin.openorchestra.1-1.inte .

1) On any content type, add a new field :
 -> Type : Choice
 -> Required : no
 -> Multiple : yes
 -> Expanded : yes
 -> Choices : 1,2,3,4
 -> Default : 1

2) Create a new content from this type and check "yes" for choice 2, "no" for other choices.

3) Submit and see the problem.

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1767 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1763
