### ISSUE TITLE
Error on 'oo_tinymce' field when reopening a form

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1664]
When opening a form that has already been opened before, a javascript error is triggered and 'oo_tinymce' fields appears as simple textareas.

To reproduce :
 - set up a content type that contains an attribute based on a oo_tinymce field,
 - go to content list related to this type,
 - click the "add" button to open the creation form,
 - click the "back to list" button,
 - click the "add" button to reopen the creation form.
-> The error is triggered and the field is displayed as a simple textarea.

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/241
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1708
thanks
