### ISSUE TITLE
Node boDirection migration missing

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1665]
A new attribute `boDirection` has been added in nodes with the 1.1.0  : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1519

I think that a migration is missing to update this attribute.

**Comment by alavieille** [comment]
I think there is no need migration for this attribute, because we can not determine in advance the direction (v or h)  for each node, Furthermore, if  this attribute is not present does not break anything.

**Comment by Thiblef** [comment]
Ok, I thought you could get the info from the templateId stored in the node.
