### ISSUE TITLE
Fatal error when moving a node if ModelGroupRole not defined

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1675]
In our database, we had some grouproles not defined for deleted nodes. I do not know where this lack of definition came from, but it lead to a fatal error when trying to move a node in the node tree.

```
Error: Call to a member function getAccessType() on null
in /var/www/ffgym-backoffice/shared/vendor/open-orchestra/open-orchestra-cms-bundle/GroupBundle/EventSubscriber
/UpdateNodeGroupRoleMoveNodeSubscriber.php at line 70
```

The problem here is that the `GroupInterface::getModelGroupRoleByTypeAndIdAndRole()` can return null but the `UpdateNodeGroupRoleMoveNodeSubscriber` does not handle this case.

**Comment by itkg-ngilain** [comment]
It seems that the problem on the data is related to your project, so we can do nothing for that. However we will throw a specific exception when taht case occurs.

**Comment by itkg-ngilain** [comment]
An exception is now fired on both 1.1 and 1.2:
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1692
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1688
