### ISSUE TITLE
Unable to add a block into an empty area in IE9

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1677]
On IE9, it is impossible to create a new page from scratch because the drag and drop function does not work when using it to put a block on an empty area.

To reproduce this :
 - create a node using based on a template (in my case I have 3 areas),
 - click on a block and begin drag,
 - drop it on any area of the page.

-> No block is created inside the area.

OO version : 1.1.1

**Comment by itkg-ngilain** [comment]
We will try to resolve the bug, but I assume that the rendering will not be the same on IE9 ou earlier version.

**Comment by alavieille** [comment]
there is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1702 and
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1700
thanks
