### ISSUE TITLE
Layout problems on node edition with IE9

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1678]
In the node edition page, on IE9, there is no top and bottom padding inside areas that already have blocks. It makes addition of a block at first or last position a bit difficult.

OO version : 1.1.1

**Comment by itkg-ngilain** [comment]
As it may be a gui issue, can you add a screenshot please ?

**Comment by itkg-canne** [comment]
![ie-area-layout-problem](https://cloud.githubusercontent.com/assets/15613074/15507134/98eb5a48-21ca-11e6-8610-dab24add3ec9.png)

**Comment by itkg-canne** [comment]
The problem is also visible on Safari on MacOSX.

**Comment by alavieille** [comment]
there is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1702 and
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1700
But i test in last version of safari in last version of MacOsX, i haven't this bug, futhermore safari isn't officially supported
thanks
