### ISSUE TITLE
Duplicated modelGroupRole

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1680]
When we update a modelGroupRole in a group (for media folders or nodes), all the modelGroupRoles are duplicated instead of being updated.

**Comment by alavieille** [comment]
it is fixed is https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1704 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1703 thanks

**Comment by Thiblef** [comment]
I'm sorry but I think it is not sufficient, the modelGroupRoles for nodes are duplicated on every modelGroupRole single update. In my opinion the problem is more global maybe on the `addModelGroupRole()` method from `Group` document with the `contains` call.
