### ISSUE TITLE
Add button for content is displayed but create content is not permitted in group

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1690]
I create a group that only has access to content.
I affect this group to my user who only this group.
Connect with this user, I see the content list however the add button is displayedbut create content is not active in this group.
Logically when I click it, an 403 error pop

I think the add button must be not displayed

In OO 1.1.1

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1716 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1735. thanks
