### ISSUE TITLE
Edit button must be not displayed is role edit page is not choose 

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1698]
I create a group that only has access to view page
I affect this group to my user who only this group.
Connect with this user, I click on page link in arbo, I see the page list. When I select a page, edit button is display and I can click on it then edit form page is display
I think the edit button must be not displayed, and page could'nt be edited

In OO 1.1.1

**Comment by alavieille** [comment]
When you click in edit button, the form is disabled ? In this case this is not a bug.
