### ISSUE TITLE
Problem when we display oo_node_choice

### ISSUE THREAD

**Issue by KevinArtus** [open-orchestra/open-orchestra-cms-bundle#1701]
File: Backoffice\Form\Type\Component\NodeChoiceType.php

You add "&#x2502" or  "&#x251C" before to display internal link.

**Comment by alavieille** [comment]
@KevinArtus can you add a context and a screenshot

**Comment by alavieille** [comment]
Have you problem with the block Media block ?

**Comment by KevinArtus** [comment]
@alavieille I've not the problem with Media Block.

**Comment by alavieille** [comment]
@KevinArtus So i think it's specific to your form
