### ISSUE TITLE
Rich text block display does not transform BBCode to HTML in BO context

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1705]
In node edition page, the rich text block displays raw BBCode (see attached image).

Open Orchestra version : 1.1

![rich-text-bbcode](https://cloud.githubusercontent.com/assets/15613074/15603462/3455c2fc-23fb-11e6-864e-e6266a7bf446.png)

**Comment by itkg-admin** [comment]
This is not an issue : the bloc is not here for a preview -> the preview functionality is made for that
