### ISSUE TITLE
Inversed workflow roles

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1707]
Workflow transitions roles and workflow profiles roles are inversed in group panels.

In a group when I set roles for Workflow transitions, the user have the right on Workflow profiles and conversely.

**Comment by itkg-ngilain** [comment]
this is fixed :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1722
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/115
