### ISSUE TITLE
Wrong area order in node edition page on first display

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1709]
When displaying the node edition page after removing cache + local-storage, areas are not displayed in the correct order.

OO version : 1.1

On first load (bad order) :
![first-load](https://cloud.githubusercontent.com/assets/15613074/15610344/0daf0300-2425-11e6-94ab-41c2cec9843e.png)

On second load (good order) :
![second-load](https://cloud.githubusercontent.com/assets/15613074/15610345/0dcbb5d6-2425-11e6-96ba-06972e6a189c.png)

**Comment by itkg-nanne** [comment]
fixed on 1.2 : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1746
fixed on 1.1: https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1747
