### ISSUE TITLE
Workflow profile with same roles

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1710]
When there are multiple workflow profiles defined with the same workflow function (for example `ROLE_FROM_DRAFT_TO_PENDING`), the user has to have every profiles activated to have the right `ROLE_FROM_DRAFT_TO_PENDING`. 

If not the WorkflowRightVoter return an `ACCESS_DENIED` cause of a bad attributes given from the `WorkflowRightStrategy`:
```
foreach ($workflowFunctions as $workflowFunction) {
   $attributes[] = $workflowFunction->getId();
 }
 if (!$this->authorizationChecker->isGranted($attributes, $document)) {
   return false;
 }
```
I reproduced this case on your 1.1 demo.

**Comment by itkg-ngilain** [comment]
This is now fixed : https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/117

Thank you for your feedback
