### ISSUE TITLE
Duplicated modelGroupRole 

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1718]
## Informations
**Orchestra Version** : 1.1
**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
The modelGroupRoles are duplicated in a group when we change the site twice (the previous fix #1680).

### Actual behavior
1. Create a group and associate it a WebSite1 => Roles and modelGroupRoles are created in Database
2. Change the WebSite to WebSite2 of the same group => Roles are not reinitilazed in form, the same Roles are visible for the new WebSite. In database the new ModelGroupRoles are added to the modelGroupRoles of WebSite1.
3. Change the WebSite to WebSite1. In database the ModelGroupRoles of WebSite1 are added to the present ModelGroupRoles: WebSite1 modelGroupRoles + WebSite2 modelGroupRoles + WebSite 3 modelGroupeRoles.

We note that modelGroupRoles are not linked to a specific siteId. Id two webSites have the same nodeId it's not possible to distinct the WebSite source.

### Expected behavior
When the WebSite of the group is changed, the form must be resetted. If the group won't have to cumulate all Roles and ModelGroupRoles they must be remove.

### Steps to reproduce the problem
1. Create a group and associate it a WebSite1 => Roles and modelGroupRoles are created in Database
2. Change the WebSite to WebSite2 of the same group => Roles are not reinitilazed in form, the same Roles are visible for the new WebSite. In database the new ModelGroupRoles are added to the modelGroupRoles of WebSite1.
3. Change the WebSite to WebSite1. In database the ModelGroupRoles of WebSite1 are added to the present ModelGroupRoles: WebSite1 modelGroupRoles + WebSite2 modelGroupRoles + WebSite 3 modelGroupeRoles.

**Comment by itkg-ngilain** [comment]
Hi, this is fix on https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1737 for 1.1 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1740 for 1.2
