### ISSUE TITLE
Content pagination links not clickable

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1742]
## Informations
**Orchestra Version** :  1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
Some content pagination links are not clickable.

### Actual behavior
1) When on page No.1 to No.3 of a list having 10+ pages, link for page No.4 is not clickable.
![page-1](https://cloud.githubusercontent.com/assets/15613074/15855035/75bbdcbc-2cad-11e6-99e8-0f8b7657b1c4.png)

2) When on page No.5 to "total - 3", link for page "n + 1"  is not clickable.
![page-5](https://cloud.githubusercontent.com/assets/15613074/15855053/9edc2106-2cad-11e6-9a65-7d106e691b1e.png)
You can notice that "Next" link is on a new line.

3) When on last page, link for page "n-1" is not clickable.
![page-26](https://cloud.githubusercontent.com/assets/15613074/15855107/f76b3992-2cad-11e6-91ca-a9b772758a0e.png)

### Expected behavior
All pagination links, except current page, are clickable.

### Steps to reproduce the problem
Got the the OO 1.1 version integration server, in news content list.
1) Bug visible on page 1.
2) Bug visible on page 5.
3) Bug visible on page 26.

**Comment by itkg-nanne** [comment]
This is not a bug. In your sample, 4, 6 and 25 are input text where you can enter the desired page.
So this ticket will not be in the roadmap. But we will make an evolution to render this functionality more readable by, for example, move the input text to current selected page.
