### ISSUE TITLE
Link to the current site field update does not have expected behaviour

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1743]
## Informations
**Orchestra Version** : 1.1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
When passing "Link to the current site" to true on a content update form, the field `siteId` is not updated, so if it does not match with current site, the contents just disappear from the list.

### Actual behavior
Defining "Link to the current site" to true on a content content update form links this content to the site on which it was created.

### Expected behavior
Defining "Link to the current site" to true on a content content update form links this content to the current site.

### Steps to reproduce the problem
1) Set "siteA" as current site (in header).
2) Create a content "content1" and defines "Linked to the current site" property to false.
3) Set "siteB" as current site (in header).
4) Update content "content1" and defines "Linked to the current site" property to true.
-> "content1" is link to "siteA" (which is not the current site).

**Comment by alavieille** [comment]
Parameter Link to the current site is now available only when you create a new content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1827
