### ISSUE TITLE
Pagination includes contents not related to site in count calculation

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1744]
## Informations
**Orchestra Version** : 1.1.1

**Issue Type**: 
- [X] Bug
- [ ] Feature request
- [ ] Question

## Description
Pagination includes contents not related to site in count calculation.

### Actual behavior
Total count in pagination is not correct.

### Expected behavior
Total count in pagination is correct.

### Steps to reproduce the problem
-> Create a new content type "Type1".
-> Set current site to "SiteA" (in header).
-> Create a content "Content1" of type "Type1" and link it to the current site.
-> Set current site to "SiteB" (in header).
-> Go in the content list page for type "Type1".
=> The list is empty but pagination says "Showing 1 to 1 of 1 entries"

**Comment by alavieille** [comment]
Your PR are merged, thanks
