### ISSUE TITLE
Impossible to set default value for button radio/choice in block with one collection field type using js

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1745]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [X] Bug
- [ ] Feature request
- [ ] Question

## Description
In context block, I would like to set default value on button radio.
Normally, there is no default value for this radio button.
Having commented on this [line](https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/BackofficeBundle/Resources/public/coffee/addPrototype.coffee#L105), it is the expected functioning 
### Actual behavior
Actually in a collection, always second value is check.

### Expected behavior
Normally, there is no default value for this radio button.

### Steps to reproduce the problem
In a block create a form with one collection field which contains radio button

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1765 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1759. thanks
