### ISSUE TITLE
Error nodes should have default BO label

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1750]
## Informations
**Orchestra Version** : 1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
When contributor access to error node edition, an empty node is automatically created, but it has no default label. User have to edit this node to define the BO label before being able to publish it.

I defined issue type to bug because the case is not correctly handled and contributor will not understand why he cannot publish the node.

### Actual behavior
When error node is created, it has no BO label.
Then, when user wants to publish it, he has just a message saying "This value should not be blank" but does not know which field is targeted by this message.

### Expected behavior
Solution can be :
 - when error node is created, it has a default BO label defined,
 - when user access an unexisting error node, the node creation form is opened, with readonly fields, and so user will have to fill BO label before being able to submit the form.

### Steps to reproduce the problem
1) Create a new website "siteA".
2) Access "Error 503" node edition page.
3) Try to publish the node.

**Comment by itkg-ngilain** [comment]
This is on our roadmap

**Comment by alavieille** [comment]
There is fixed in 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1828
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/622
thanks
