### ISSUE TITLE
Unable to access some buttons if node label is too long

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1756]
## Informations

**Orchestra Version** : 1.1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question
## Description

When a node BO label is too long, the text is displayed in front of buttons in node edition page. It makes them not clickable.
### Actual behavior

Buttons "edit" and "delete" of node edition page are not clickable when BO label of a node is too long.
Note that the problem appears also on a node having a short BO label but located in a deep level of hierarchy.
### Expected behavior

Text that overflows available space is hide.
### Steps to reproduce the problem

1) Create a node with a BO label "This is a very long BO label, I am sure it will be displayed in front of buttons, and I will not be able to click them.".
2) Go to the node edition page.

**Comment by itkg-ngilain** [comment]
Thank you for your feedback, this problem will be solve as soon as possible.

**Comment by alavieille** [comment]
This issue isn't longer valid with 2.0
