### ISSUE TITLE
Duplication of group_roles

### ISSUE THREAD

**Issue by mmbourgc** [open-orchestra/open-orchestra-cms-bundle#1761]
## Informations

**Orchestra Version** : 1.1.1

**Issue Type**: 

- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
On node creation, same group roles are duplicated several times. 

### Actual behavior
As said before when you create multiple nodes, group roles are created several times for one node. It doesn't matter if your website is made of few nodes. But for my website made of nearly 70 nodes and 15 media folders, the users_group collection weight is nearly 6Mo (with 2 groups). This leads to timeouts when you create a new node even if the node is created.

### Expected behavior
To have only one group role for one node id/type/role.

### Steps to reproduce the problem
Create multiple nodes

### Solution
It seems that the "contains" function of class Doctrine\ODM\MongoDB\PersistentCollection is not working as expected in function addModelGroupRole of class OpenOrchestra\GroupBundle\Document\Group. 

The working function (for me) looks like that : 
`

    public function addModelGroupRole(ModelGroupRoleInterface $modelGroupRole)
    {
        $index = null;
        foreach ($this->modelRoles as $key => $modelRole) {
            if ($modelRole->getType() == $modelGroupRole->getType() && $modelRole->getId() == $modelGroupRole->getId() && $modelRole->getRole() == $modelGroupRole->getRole()) {
                $index = $key;
            }            
        }        
        
        if ($index !== null) {
            $this->modelRoles[$index]->setGranted($modelGroupRole->isGranted());
        } else {
            $this->modelRoles->add($modelGroupRole);
        }
    }
`

However i'm not sure it works the way you want to...

**Comment by alavieille** [comment]
i think this issue is a duplicated of https://github.com/open-orchestra/open-orchestra-cms-bundle/issues/1718. Normally this is fixed with this pull request 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1737/files

**Comment by alavieille** [comment]
@mmbourgc  Open orchestra version 1.1.2 is out with lot of bugfix (http://open-orchestra.readthedocs.io/en/1.1/changelog/CHANGELOG-1.1.1-to-1.1.2.html), can you check if you have always the bug

**Comment by mmbourgc** [comment]
Version 1.1.2 fixed the problem. With performance improvement too. Nice job.
