### ISSUE TITLE
Inconsistence between item categories in menu and in rights management

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1780]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
Items in menu and rights management are separated into 2 categories : "Contribution" and "Administration".
In menu, the "Templates" item is in "Administration" category. Corresponding item in rights management (in groups) is named "Page template" and is in "Contribution" category.
It could be clearer to harmonize categorization and naming.

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1796 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1788 thanks
