### ISSUE TITLE
Backport request of #1543: Invalid CSRF Token

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-cms-bundle#1781]
## Informations
**Orchestra Version** : 
1.0

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
CSRF error on form submission.

Same as #1543 fixed by #1660 / #1670

**Comment by alavieille** [comment]
I don't understand what you want ? In issue they have not bug. the problem of CSRF is an issue of their project. We have add just a new feature to prevent display of forms in fullscreen when there is an javascript error when form is submitted

**Comment by ngilain** [comment]
The fix is available in 1.1 but no backport will be made for 1.0
