### ISSUE TITLE
Unable to define a block prefix inside block forms.

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1787]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
If a block prefix is defined inside a block form type (a strategy having the tag `name: open_orchestra_backoffice.generate_form.strategy`) using the method `getBlockPrefix` (see `\Symfony\Component\Form\AbstractType::getBlockPrefix()`), an exception is thrown.
```
An exception has been thrown during the rendering of a template ("Unable to render the form as none of the following blocks exist: "_oo_block_widget", "oo_block_widget", "oo_block_widget", "form_widget".") in "OpenOrchestraBackofficeBundle:Form:form_div_layout.html.twig". 
```

### Steps to reproduce the problem
Adds this method inside `OpenOrchestra\Backoffice\GenerateForm\Strategies\AbstractBlockStrategy` and try to open a block configuration form inside the node edition page.
```
    public function getBlockPrefix() {
        return 'oo_block';
    }
```

**Comment by alavieille** [comment]
This is a bug of symfony when you used the deprecated syntax of form. We need the block prefix is different from the name of the parent.

**Comment by itkg-canne** [comment]
The usage of deprecated methods is also on OO side but it seems not simple to do something that is matching the 2.8+ way to do forms in Symfony.
