### ISSUE TITLE
Define a priority in all event subscribers

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1790]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**:
- [ ] Bug
- [x] Feature request
- [ ] Question

## Description
Sometimes, it is important to be able to control execution order of event subscribers. If OO event subscribers execution priority was defined, it could be easier to control execution priority of a new subscriber.

**Comment by ngilain** [comment]
You can do this by overriding the OO services
