### ISSUE TITLE
Block label is no longer automatically defined

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1791]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
Block label definition used to be done automatically. It is no longer the case.

### Actual behavior
Block label definition has to be done manually.

### Expected behavior
Block label definition is done automatically.

### Steps to reproduce the problem
1 - Add a block on a node.
2 - Edit the block.
3 - See that label field has no value.

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1806 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1804. thanks
