### ISSUE TITLE
Add external URL

### ISSUE THREAD

**Issue by KevinArtus** [open-orchestra/open-orchestra-cms-bundle#1793]
## Informations

**Orchestra Version** : 
1.1.2
**Issue Type**: 

- [ ] Bug
- [X] Feature request
- [ ] Question

### Actual behavior
When a user have to add a URL, he should do it like : http://www.google.fr

### Expected behavior
When we consider that the user is a little bit "noob" with this, it could be easier to allow him to add a URL without http:// or https://
So, he could add an URL : www.google.fr

### Steps to reproduce the problem
![capture du 2016-06-29 10-52-14](https://cloud.githubusercontent.com/assets/3033900/16446383/8d8a4018-3de7-11e6-847b-72f086ea2960.png)

**Comment by alavieille** [comment]
Your issue isn't very explicit. what part you speak ?  the redirections ?

**Comment by KevinArtus** [comment]
@alavieille Sorry, look at picture i've added. It is more explicit.

**Comment by alavieille** [comment]
@KevinArtus i think this form isn't a feature of open orchestra but a feature of your project. No ?
