### ISSUE TITLE
Performances problems when publishing a node having a lot of children

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1797]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
When publishing a node having a lot of children, process takes too much time and use too much memory. Performances are also getting worse when adding site aliases.

### Actual behavior
In our case, the publishing process fails after a long time because it needs to use more memory than allowed by the server (128MB).

### Expected behavior
Publishing process does not fail.

### Steps to reproduce the problem
1) Create a website.
2) Create a lot of pages (100+), on multiple levels of hierarchy (3+), and publish them.
3) Add a lot of aliases to the site (10+).
4) Create a new version of root node and try to publish it.

## Analysis
The problem is located in the process that update routes. When a node status change, it just remove and recreate all routes of this node and its children. Fetching children uses one request by hierarchy level, removing routes uses a request by route to remove, and recreating route uses a request by route to add.

There are a lot of optimizations that can be easily made :
1) There is no need to refresh routes if the node status change does not change the publication state.
2) There is no need to refresh routes if the route pattern of the node has not change.
3) There is no need to refresh routes of children that uses an absolute route pattern.
4) A route is generated for each version of children. It is useless to create multiple routes if each version uses the same route pattern.
5) All informations of the node tree are not used. Hydrating all nodes of the tree takes a lot of resources. Maybe fetching only needed informations and work with simplified objects could be a good solution to improve memory usage.

**Comment by ngilain** [comment]
We will try to optimize this

**Comment by itkg-nanne** [comment]
fixed in :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1819
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/619
https://github.com/open-orchestra/open-orchestra-model-interface/pull/211
