### ISSUE TITLE
CurrentlyPublished flag on content duplication

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1813]
## Informations

**Orchestra Version** : 1.1 

**Issue Type**: 

- [x] Bug
- [ ] Feature request
- [ ] Question

## Description
The `currentlyPublished` flag isn't set in `duplicateContent()` from `ContentManager`. So when the content is published and you create a new version of it, the  `currentlyPublished` flag value stay to `true`. 
### Actual behavior
On content duplication, if the content is published, the new version `currentlyPublished` flag is set to `true`.
### Expected behavior
On content duplication, the new version `currentlyPublished` flag is set to `false`.
### Steps to reproduce the problem
1. Publish a content
2. Create a new version of this content
3. Check the currentlyPublished flag of the new content version in database

**Comment by alavieille** [comment]
There is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1826 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1824. thanks
