### ISSUE TITLE
Performance problems when number of nodes and media folder increases

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1835]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 

- [x] Bug
- [ ] Feature request
- [ ] Question

## Description

We encounter performance problems loading the left menu when number of node and media folder increases.
There is two optimisation that can be de done:
- The model group roles storage can be enhanced adding an index for each modelGroupRoles composed with the type, the role and the id. With taht, the time of execution to get them will be reduce (`OpenOrchestra\GroupBundle\Document\Group::getModelGroupRoleByTypeAndIdAndRole()`). Here an example of profile where `getModelGroupRoleByTypeAndIdAndRole` takes many time :
https://blackfire.io/profiles/a970a3c5-3a84-45b9-8466-1d576e8ec6f0/graph

- Load the left menu with an ajax method to stop loading every nodes and media folder.

### Actual behavior
Dashboard page takes too much time to load.
### Expected behavior
Dashboard page takes less time to load.
### Steps to reproduce the problem
Contribute many nodes and many media folder.

**Comment by alavieille** [comment]
Optimization of model group role is in this PR 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1839
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/229
But the load of the left menu is only planned for the version 1.1
