### ISSUE TITLE
Form submission does not handle errors

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1857]
## Informations

**Orchestra Version** : 1.0, 1.1

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question
### Actual behavior

When submiting a form using the "submitAdmin" view extension, it's not possible to introduce custom behavior. Moreover, on version 1.0, error codes are not managed, and only 403 are managed in later versions. Therefore, when an error occurs during form submission, the page becomes unresponsive and the spinner continues loading indefinitely.
### Expected behavior
- Errors should be managed
- Some extension points should be provided in order to customize the behavior when getting a response
### Steps to reproduce the problem

Submit a form which throws an error on the server side (other than 403).

**Comment by itkg-nanne** [comment]
submitAdminView is in extendedView. It is possible to extend the targeted view with another "js trait".

**Comment by itkg-nanne** [comment]
There are many ways to deactivate submitAdmin, for example, by changing the css class on the submit button (actually css class submit_form is required to activate submitAdmin behavior) or by using appViewConfigurator to use a custom view not using the submitAdmin Extended View or by manually adding to the targeted view an extended view which defines the addEventOnSave method (last loaded method will override all others). Is it ok for you @juchi ?

**Comment by juchi** [comment]
Ok i'll take a look to these options

**Comment by alavieille** [comment]
This issue isn't longer valid with 2.0.
