### ISSUE TITLE
Block usage informations are often outdated in node document

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1863]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 

- [x] Bug
- [ ] Feature request
- [ ] Question

### Actual behavior
In node document, usage of blocks is not updated when a new version of a node is created or when a new node is created by copying an existing one.

### Expected behavior
Information about block usage is up to date an complete.

### Steps to reproduce the problem
1) Create a blank node (NodeA version 1) from a template.
2) Add a block.
3) Create a new version of this node (NodeA version 2).
-> In the version 2 of NodeA, blocks[0][areas][0][nodeId] contains the Mongo Id of "NodeA version 1" instead of "NodeA version 2".
4) Create a new node (NodeB version 1) based on a copy of NodeA version 1.
-> In the version 1 of NodeB, blocks[0][areas][0][nodeId] contains the Mongo Id of "NodeA version 1" instead of "NodeB version 1".

**Comment by itkg-nanne** [comment]
OO stocks or 0 or transverse for nodeId and never MongoId
