### ISSUE TITLE
Performances issues due to voters

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1873]
## Informations
**Orchestra Version** : 1.1.2

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question

## Description
On OO version 1.1.2, voter execution can take a lot of time to check rights that sometimes seems not used at all.
For example, when the BO requests `/api/node/root/list-version?language=zn` to display the list of versions, the `DeleteStatusVoter` is called for each version. The `vote` operation takes 100ms on my machine and does a Mongo request to check usage of this node version. But, if I am not wrong, this vote operation result is not used in this case.
It could be nice to optimize performances of voters.

### Steps to reproduce the problem
1) Log in into BO.
2) Create lot of versions of your root node in english.
3) Profile `/api/node/root/list-version?language=en`.

**Comment by ngilain** [comment]
Thank you for your feedback.

You are right those operations are sometimes expensive and not always required according to the context of the transformation (api request).
In v1.1, we have filtered the status hydratation according to the context to prevent expansive and useless call to the voters in https://github.com/open-orchestra/open-orchestra-cms-bundle/commit/1b50ec39fbac41ad5ad5811e93703d33431ad328

A lot more is to come in the v2, as you can see in the followings PR :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1886
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/295
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1939
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1940
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1941
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1942
