### ISSUE TITLE
Give ability to manualy delete a version of a node or a content

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1874]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question
## Description

Our client wants to be able to delete a version of a node manually for multiple reasons (really old version, obsolete draft, ...). Some nodes that are often updated can have 10+ version created each month.
A side effect of the impossibility of deleting versions of a node is that it is not possible to delete obsolete media that are linked to it.

**Comment by alavieille** [comment]
It's now possible in 2.0
