### ISSUE TITLE
Enable usage of block default configuration for all fields

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1888]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question
## Description

For now, default block configuration (`OpenOrchestra\Backoffice\GenerateForm\Strategies\GenerateFormInterface::getDefaultConfiguration()`) only applies to attributes (see `OpenOrchestra\ApiBundle\Transformer\BlockTransformer::reverseTransformToArray()`). Even if fields are pre-defined when opening the form, values are not stored at the good place unless the block configuration form is submitted at least once. Indeed, the are stored in `attributes` collection instead of being store in block root.

For information, it affects the definition of block cache maxAge defaut configuration ( https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1843/files ).

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1969
