### ISSUE TITLE
NodeId or MongoId in the node previews URLs?

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-cms-bundle#1961]
## Informations

**Orchestra Version** : 1.1.5

**Issue Type**: 

- [x] Bug
- [ ] Feature request
- [x] Question
## Description

While updating my project from 1.1.2 to 1.1.5 I noted a difference in the node preview links.

This difference was introduced here: https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/1.1/ApiBundle/Transformer/NodeTransformer.php#L242
The `$node->getNodeId()` was replaced by `$node->getId()` in the v1.1.5. 

Is this normal? Is this parameter usefull? 

Thanks
### Actual behavior

The node preview url contains the mongoID of the node.
### Expected behavior

The node preview url contains the nodeID of the node?
### Steps to reproduce the problem

Click the preview button on a node in the back office and check the URL.

**Comment by ngilain** [comment]
@Thiblef : This has been fix on both v1.1 and v1.2 by removing the requirement of node id to generate the preview link

Thank you for your feedback
