### ISSUE TITLE
Add PHP 7.0 support

### ISSUE THREAD

**Issue by cedric-anne** [open-orchestra/open-orchestra-cms-bundle#2364]
## Informations
**Orchestra Version** : 2.0

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question

## Description
It could be usefull to be able to install OO on a server having PHP 7.0.

### Actual behavior
Required PHP version is 5.6.x.

### Expected behavior
Required PHP version can be 5.6.x or 7.0.x.

### Steps to reproduce the problem
Install OO on a server having PHP 7.0.x version.

**Comment by c-anne** [comment]
`composer.lock` files of `open-orchestra` and `open-orchestra-front-demo` have to be updated when all dependencies will be merged.
