### ISSUE TITLE
Missing abstract method in AbstractBlockContentTypeSubscriber

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#759]
The AbstractBlockContentTypeSubscriber listens two events and binds two methods to them (preSetData and preSubmit) but does not declare their prototype, so derived class are not forced to implement them.

**Comment by nicolasThal** [comment]
This pr will fix this https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/760
