### ISSUE TITLE
The FullPageFormView is required to have a domContainer option

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#813]
It's not possible to create a FullPageFormView without the domContainer option, as it is used in the render() method.
However, as the name states, "options" should be optional, so I guess a default value would be a good way to improve things. #container is the ID that seems to be used in all cases anyway.

**Comment by itkg-nanne** [comment]
I would rather supress all domContainer and append view in parent.

**Comment by juchi** [comment]
That's an option, but the rendering process should be thought again for this change.

**Comment by itkg-ngilain** [comment]
Supress all domContainer will not work beacuse of the asynchronous loading of templates.

As a view loads asynchronously its templates, the parent can't know when to append the child. The only way to be sure the html has been loaded is to let the children draw itself when it's ready (that the reason why the render method is automatically called when all templates are loaded).

Alternativly, maybe the DomContainer should not be an option, but a separated parameter of the orchestraView, always requested as a view must be included somewhere in the DOM.

**Comment by itkg-nanne** [comment]
domContainer could maybe be suppressed by binding on an event which is triggered when view is rendered.

**Comment by itkg-nanne** [comment]
If backboneParentView create a backBoneSonView, backboneParentView could implement  backboneParentView.listenToOnce(backBoneSonView, 'templateGenerated', appendToDom). So after orchestraView->onReady, backBoneSonView send 'templateGenerated' event triggered by backboneParentView which add backBoneSonView template to Dom with appendToDom function.
With this workflow, we could remove all domContainer parameter from OpenOrchestra js.
Is it ok for you @juchi ? (should be done in OpenOrchestra js Refacto)

**Comment by juchi** [comment]
Are we talking about two new classes (parent and son views) ? If so, this seems incorrect because then a son cannot have children ?
Otherwise, i did not understand the solution.

**Comment by itkg-nanne** [comment]
without new classes, just an example.

var ParentView;

ParentView = OrchestraView.extend({
    initialize: function(options) {
	this.reduceOption(options, ['myParentOption0', 'myParentOption1', ...]);
        this.loadTemplates(["myParentTemplate"]);
    },
    render: function() {
        this.setElement(this.renderTemplate("myParentTemplate", this.options));
        //$('body').append(this.$el);
	sonView = new SonView(this.options);
	this.listenToOnce(sonView, 'end_render', this.addSonToDom);
    },
    addSonToDom: function(sonView) {
        $('#selector', this.$el).append(sonView.$el);
    }
});

var SonView;

SonView = OrchestraView.extend({
    initialize: function(options) {
        this.reduceOption(options, ['mySonOption0', 'mySonOption1', ...]);
        this.loadTemplates(["mySonTemplate"]);
    },
    render: function() {
        this.setElement(this.renderTemplate('mySonTemplate', this.options));
    }
});

render() is called in onTemplateLoaded in OrchestraView and could be followed by this.trigger('end_render', this)

The idea is that a view create by an other one send that it's render is finished and the creator push the render in the Dom. No need domContainer.
With listenToOnce, only the creator will hear the event and debind after rending.

Only problem, i see,  is that end_render event could be sended before listenToOnce (all templates in local storage). This could be fixed by a lifeCycle. An override of listenToOnce could test if son is after the event 'end_render' in his lifeCycle and call directly the callback. If not it uses normal listeToOnce.

Is it ok for you @juchi ?

**Comment by juchi** [comment]
Actually i'm not sure that replacing the view's $el is the good way to go with backbone views, because you loose the advantage of having a fixed DOM element for a given view. Views hierarchy could probably be handled smoothly by creating the child view in the parent, and appending the child's $el to the parent's, so no need to use events.
A simple example of such pattern : http://ianstormtaylor.com/rendering-views-in-backbonejs-isnt-always-simple/

**Comment by itkg-nanne** [comment]
Not sure that this pattern could be used as getting template is async and child's render too, the source of our problem. @juchi

**Comment by juchi** [comment]
That's why I said replacing the $el object when the rendering is done cannot work here. If it's not replaced when the rendering is done I think it should work as if everything was synchronous.

**Comment by itkg-nanne** [comment]
Ok, I see. But I'm not sure, it could be easily done. Take area._tpl.twig, <li> get datas which need twig trans(). How to use el : 'li' in backbonView in a such case. Take blocksPanel._tpl.twig, there is no main container for this template. How to use el whithout redesign all template....

**Comment by juchi** [comment]
Yes you're right, some specific use cases will probably deserve some more thoughts.

**Comment by alavieille** [comment]
This issue isn't longer valid with the refacto of all js in 2.0.
