### ISSUE TITLE
Error when using "back to list" on new content creation

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#837]
I try to create a new content by clicking the "Add" button. I don't save my form and just click "back to list" on the subsequent page, then the "loading" spinner is displayed and the page doesn't load.
In the console there is a JS error "link.data(...) is undefined".

**Comment by itkg-alavieille** [comment]
This pr will fix this https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/839
