### ISSUE TITLE
[Insight] Unused use statement should be avoided - in UserAdminBundle/Form/Type/UserType.php, line 9

### ISSUE THREAD

**Issue by nicolasThal** [open-orchestra/open-orchestra-cms-bundle#842]
**[in UserAdminBundle/Form/Type/UserType.php, line 9](https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/60e23802ac2a7b59031233380cca41558df05157/UserAdminBundle/Form/Type/UserType.php#L9)**

> The class `Twig_Environment` is declared but never used. You should remove the `use` statement.

```php

use OpenOrchestra\BackofficeBundle\EventSubscriber\AddSubmitButtonSubscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Twig_Environment;

/**
 * Class UserType
 */
class UserType extends AbstractType
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/67012b2b-c9c4-41bc-a13d-9981f2244bf7/analyses/211)_

**Comment by itkg-alavieille** [comment]
this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/843 fix it
