### ISSUE TITLE
[Insight] Boolean should be compared strictly - in …/ContentTypeSubscriber.php, line 124

### ISSUE THREAD

**Issue by nicolasThal** [open-orchestra/open-orchestra-cms-bundle#899]
**[in BackofficeBundle/EventSubscriber/ContentTypeSubscriber.php, line 124](https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/dc86b86f36db060571f82da63ef963d4717d5511/BackofficeBundle/EventSubscriber/ContentTypeSubscriber.php#L124)**

> With booleans, only strict comparison (with `===` operator) should be used to lower bug risks and to improve performances.

```php
                'mapped' => false,
            ),
            $this->getFieldOptions($contentTypeField)
        );

        if (isset($fieldParameters['required']) && $fieldParameters['required'] == true) {
            $fieldParameters['constraints'] = new NotBlank();
        }

        $form->add(
            $contentTypeField->getFieldId(),
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/67012b2b-c9c4-41bc-a13d-9981f2244bf7/analyses/434)_

**Comment by itkg-alavieille** [comment]
fix in https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/898
