### ISSUE TITLE
[Insight] Boolean should be compared strictly - in BackofficeBundle/Manager/NodeManager.php, line 80

### ISSUE THREAD

**Issue by nicolasThal** [open-orchestra/open-orchestra-cms-bundle#959]
**[in BackofficeBundle/Manager/NodeManager.php, line 80](https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/219e4050189d7ca332106bbcb3d37c656195e4b3/BackofficeBundle/Manager/NodeManager.php#L80)**

> With booleans, only strict comparison (with `===` operator) should be used to lower bug risks and to improve performances.

```php
     */
    public function duplicateNode($nodeId, $siteId, $language)
    {
        $node = $this->nodeRepository->findOneByNodeIdAndLanguageAndVersionAndSiteId($nodeId, $language, $siteId);
        $status = $this->getEditableStatus($node);
        if ($status == null) {
            $status = $this->statusRepository->findOneByInitial();
        }
        $newNode = $this->nodeManager->duplicateNode($nodeId, $siteId, $language, $status->getId());
        $this->updateBlockReferences($node, $newNode);

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/67012b2b-c9c4-41bc-a13d-9981f2244bf7/analyses/660)_

**Comment by itkg-alavieille** [comment]
fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/969
